"""message

Revision ID: 00292798faaa
Revises: 4b942755318c
Create Date: 2025-02-06 00:19:05.004289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00292798faaa'
down_revision = '4b942755318c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
